#library(Seurat)
#library(SeuratData)
#library(SeuratWrappers)
#library(Azimuth)
#library(ggplot2)
#library(patchwork)
#options(future.globals.maxSize = 1e+10)

system2("pwd")
system2("cd", args = "/rsrch7/home/bcb/SCLC/yxi/SCLC.scRNAseq/Patient_biopsy/RData/by_sample/")